In [2]:
import pandas as pd

df = pd.read_csv("jobs.csv")
df

,Unnamed: 0,Created_date,Due_date,Job_id,Payment_type,Budget,Job_title,Category,Subcategory,Job_description,...,Link_of_employer,Employer_id,No_of_quotes,Link_of_quoters,No_of_Premium_quotes,Link_of_premium_quoters,No_of_inviited,Link_of_invited_freelancers,No_of_Hired,Link_of_hired_freelancers
0,0,"Nov 16, 2020","December 18, 2020",1731482,Fixed Price,[' Under $250'],Society Management app (Android/IOS),Programming & Development,Apps & Mobile,We are looking for mobile app developer (fulls...,...,https://www.guru.com/work/detail/1731482,1731482,9,"['https://www.guru.com/freelancers/scopic', 'h...",0,[],0,[],0,[]
1,1,"Nov 16, 2020","Hiring more, till Dec 17, 2020",1731479,Fixed Price or Hourly,NaN,GPRS tracking device/Server,Programming & Development,Programming & Software,I want to be able to track vehicles thus neede...,...,https://www.guru.com/work/detail/1731479,1731479,7,['https://www.guru.com/freelancers/ravi-deshmu...,0,[],1,['https://www.guru.com/freelancers/spinlogics'],1,['https://www.guru.com/freelancers/ravi-deshmu...
2,2,"Nov 16, 2020","December 16, 2020",1731480,Fixed Price,[' Under $250'],create + edit two certificates,Design & Art,Graphic Design,I need a graphics artist/photoshop/illustrator...,...,https://www.guru.com/work/detail/1731480,1731480,23,['https://www.guru.com/freelancers/ammaramjad'...,0,[],0,[],0,[]
3,3,"Nov 16, 2020","December 16, 2020",1731476,Fixed Price,[' $1k-$2.5k'],2 WEBSITE DEVELOPMENT,Programming & Development,Web Development & Design,We need two website design\n\n1. This process ...,...,https://www.guru.com/work/detail/1731476,1731476,26,['https://www.guru.com/freelancers/amazon-soft...,0,[],0,[],0,[]
4,4,"Nov 16, 2020","December 16, 2020",1731463,Fixed Price,[' Under $250'],digital coloring work for comic,Design & Art,Photo / Image Restoration & Editing,looking for digital coloring work for kids com...,...,https://www.guru.com/work/detail/1731463,1731463,13,['https://www.guru.com/freelancers/tania-arts'...,0,[],0,[],0,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,1460,"Feb 11, 2017","June 21, 2030",1331813,Hourly,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",Help create networks from RNA Seq. data,Other,NaN,Patient Tutor to teach Time Series Cell Cycle ...,...,https://www.guru.com/work/detail/1331813,1331813,14,['https://www.guru.com/freelancers/bonzai-crea...,0,['https://www.guru.com/freelancers/bonzai-crea...,0,[],0,[]
1461,1461,"Dec 14, 2016","May 01, 2023",1314351,Hourly,"[' $5 - $10 ', ' 30+ hrs/wk ', ' 6+ months']",SEO my site who sell instagram followers,Sales & Marketing,NaN,Project Description\n\nI need my website showi...,...,https://www.guru.com/work/detail/1314351,1314351,90,['https://www.guru.com/freelancers/raheela-khu...,0,[],0,['https://www.guru.com/freelancers/raheela-khu...,0,[]
1462,1462,"Mar 14, 2016","April 27, 2021",1225615,Hourly,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",Analyzing microarray time series data,Other,NaN,Help in analyzing yeast microarray time series...,...,https://www.guru.com/work/detail/1225615,1225615,19,['https://www.guru.com/freelancers/yesesri-che...,0,[],0,[],0,[]
1463,1463,"Sep 30, 2015","December 31, 2023",1174444,Fixed Price,[' $500-$1k'],"Need a Custom, Print-Ready Folder Design",Design & Art,NaN,I need a presentation folder designed for an e...,...,https://www.guru.com/work/detail/1174444,1174444,100,['https://www.guru.com/freelancers/live-deftso...,1,[],0,[],0,[]
1464,1464,"Nov 26, 2020","November 30, 2020",1731424,Fixed Price,[' $250-$500'],get a Google developer account,Programming & Development,Apps & Mobile,"1. Programming, for a game App\n2. At least 8 ...",...,https://www.guru.com/work/detail/1731424,1731424,4,['https://www.guru.com/freelancers/mahmoud-ham...,0,[],0,[],0,[]

In [4]:
df['Category'].unique

<bound method Series.unique of 0       Programming & Development
1       Programming & Development
2                    Design & Art
3       Programming & Development
4                    Design & Art
                  ...
1460                        Other
1461            Sales & Marketing
1462                        Other
1463                 Design & Art
1464    Programming & Development
Name: Category, Length: 1465, dtype: object>

In [9]:
df2 = df[['Job_title', 'Job_description', 'Budget', 'Category' , 'Subcategory']]
df2

,Job_title,Job_description,Budget,Category,Subcategory
0,Society Management app (Android/IOS),We are looking for mobile app developer (fulls...,[' Under $250'],Programming & Development,Apps & Mobile
1,GPRS tracking device/Server,I want to be able to track vehicles thus neede...,NaN,Programming & Development,Programming & Software
2,create + edit two certificates,I need a graphics artist/photoshop/illustrator...,[' Under $250'],Design & Art,Graphic Design
3,2 WEBSITE DEVELOPMENT,We need two website design\n\n1. This process ...,[' $1k-$2.5k'],Programming & Development,Web Development & Design
4,digital coloring work for comic,looking for digital coloring work for kids com...,[' Under $250'],Design & Art,Photo / Image Restoration & Editing
...,...,...,...,...,...
1460,Help create networks from RNA Seq. data,Patient Tutor to teach Time Series Cell Cycle ...,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",Other,NaN
1461,SEO my site who sell instagram followers,Project Description\n\nI need my website showi...,"[' $5 - $10 ', ' 30+ hrs/wk ', ' 6+ months']",Sales & Marketing,NaN
1462,Analyzing microarray time series data,Help in analyzing yeast microarray time series...,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",Other,NaN
1463,"Need a Custom, Print-Ready Folder Design",I need a presentation folder designed for an e...,[' $500-$1k'],Design & Art,NaN
1464,get a Google developer account,"1. Programming, for a game App\n2. At least 8 ...",[' $250-$500'],Programming & Development,Apps & Mobile

In [17]:
df2['Budget']

0                                         [' Under $250']
1                                                     NaN
2                                         [' Under $250']
3                                          [' $1k-$2.5k']
4                                         [' Under $250']
                              ...
1460    [' No rate specified ', ' 10-30 hrs/wk ', ' 6+...
1461         [' $5 - $10 ', ' 30+ hrs/wk ', ' 6+ months']
1462    [' No rate specified ', ' 10-30 hrs/wk ', ' 6+...
1463                                        [' $500-$1k']
1464                                       [' $250-$500']
Name: Budget, Length: 1465, dtype: object

In [22]:
new = df2["Budget"].str.split(",", n = 2, expand = True)

In [23]:
df2["First"] = new[0]
df2["Second"] = new[1]
df2["Third"] = new[2]

C:\Users\akshay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\akshay\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\akshay\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [25]:
df2[['Budget', 'First', 'Second', 'Third']]

,Budget,First,Second,Third
0,[' Under $250'],[' Under $250'],None,None
1,NaN,NaN,NaN,NaN
2,[' Under $250'],[' Under $250'],None,None
3,[' $1k-$2.5k'],[' $1k-$2.5k'],None,None
4,[' Under $250'],[' Under $250'],None,None
...,...,...,...,...
1460,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",[' No rate specified ',' 10-30 hrs/wk ',' 6+ months']
1461,"[' $5 - $10 ', ' 30+ hrs/wk ', ' 6+ months']",[' $5 - $10 ',' 30+ hrs/wk ',' 6+ months']
1462,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",[' No rate specified ',' 10-30 hrs/wk ',' 6+ months']
1463,[' $500-$1k'],[' $500-$1k'],None,None
1464,[' $250-$500'],[' $250-$500'],None,None